Update to libminesweeper v1.0.0
rotmoset/gb-mines pull request #2
Opened 2016-10-19 21:26 UTC by accatyyc

New libminesweeper API that looks a lot better.

Will also distribute mines in `minesweeper_init` instead of when opening the first tile. This should remove the slight lag because of random number generation.

2016-10-19 21:45 UTC, andreasjhkarlsson requested changes
Some things need fixing.

2016-10-19 21:45 UTC, rotmoset commented on game.c
> +			if (game->state == MINESWEEPER_PENDING_START)
Please re-add the comment.

2016-10-19 21:45 UTC, rotmoset commented on game.c
> -				seed_prng();
This should not be removed. Without it, only 256 unique games are possible.

2016-10-19 21:45 UTC, rotmoset commented on game.c
> +	unsigned x, y; minesweeper_get_tile_location(game, tile, &x, &y);
Hmm, okejdå.

2016-10-20 06:39 UTC, accatyyc commented
The PRNG-concerns should now be fixed

2016-10-20 10:42 UTC, rotmoset commented
This doesn't work as [button_pressed doesn't return until the button has been released](https://github.com/rotmoset/gb-mines/blob/master/utils.c#L16). Also, using a flag here is not needed. A simple while loop would be simpler, like so:

```
if (joypad() & J_START)
{
   seed_prng();
   while(joypad()&J_START); // Block until release
   seed_prng();
  // ...
}
```

2016-10-20 10:47 UTC, rotmoset commented
Note: Passing '0' as the second parameter to button_pressed makes it return immedietely without waiting for release.

2016-10-20 15:52 UTC, accatyyc commented
Concerns fixed.

2016-10-20 22:01 UTC, merged